const express = require('express');
const router = express.Router();
const AuthController = require('../controllers/AuthController');
const { authenticate, optionalAuth } = require('../middlewares/auth');
router.post('/login', AuthController.login);
router.post('/refresh', AuthController.refreshToken);
router.post('/logout', authenticate, AuthController.logout);
router.get('/verify', AuthController.verifyToken);
router.get('/me', authenticate, AuthController.getCurrentUser);
router.get('/profile', authenticate, AuthController.getProfile);
router.post('/change-password', authenticate, AuthController.changePassword);
router.get('/token-info', authenticate, AuthController.getTokenInfo);
router.get('/public', AuthController.publicEndpoint);
router.post('/register', AuthController.register);
router.post('/forgot-password', AuthController.forgotPassword);
router.post('/reset-password', AuthController.resetPassword);
module.exports = router;
